# Generated by Django 2.1.1 on 2019-06-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('type', models.IntegerField(max_length=5)),
                ('class_number', models.CharField(max_length=20)),
                ('pass_word', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=100)),
                ('academy', models.CharField(max_length=20)),
            ],
        ),
    ]
