# Generated by Django 2.1.1 on 2019-06-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0003_auto_20190625_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('invite_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('creator_id', models.CharField(max_length=20)),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('class_room_number', models.CharField(max_length=20)),
            ],
        ),
    ]
