# Generated by Django 2.1.1 on 2019-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0005_student2course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=20)),
                ('uper_id', models.CharField(max_length=20)),
                ('up_time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
