# Generated by Django 2.1.1 on 2019-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0007_auto_20190625_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('up_time', models.TimeField(auto_now_add=True)),
                ('uper_id', models.CharField(max_length=20)),
            ],
        ),
    ]
