# Generated by Django 2.1.1 on 2019-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0012_auto_20190626_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='../media'),
        ),
    ]
