# Generated by Django 2.1.1 on 2019-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0014_auto_20190626_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='static'),
        ),
    ]
