# Generated by Django 2.1.1 on 2019-06-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0015_auto_20190626_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='2', upload_to='static'),
        ),
    ]
