# Generated by Django 2.1.1 on 2019-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0018_auto_20190626_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='media/default.jpg', upload_to='media'),
        ),
    ]
