# Generated by Django 2.1.1 on 2019-06-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0029_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='communication',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
