# Generated by Django 2.1.1 on 2019-06-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0030_auto_20190628_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicaitonitem',
            name='up_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
