# Generated by Django 2.1.1 on 2019-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0031_communicaitonitem_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.FileField(default='media/home_work_default.jpg', upload_to='media/answers'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
