# Generated by Django 2.1.1 on 2019-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0032_auto_20190628_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=-1),
        ),
    ]
