# Generated by Django 2.1.1 on 2019-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0036_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
