# Generated by Django 2.1.1 on 2019-06-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default='something', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(),
        ),
    ]
