# Generated by Django 2.1.1 on 2019-06-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0002_auto_20190625_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
