# Generated by Django 2.1.1 on 2019-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2Course',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
    ]
