# Generated by Django 2.1.1 on 2019-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0006_inform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
