# Generated by Django 2.1.1 on 2019-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0009_auto_20190625_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicaitonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uper_id', models.CharField(max_length=20)),
                ('communication_id', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_code', models.CharField(max_length=10)),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_id', models.CharField(max_length=20)),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='course',
            name='span',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
