# Generated by Django 2.1.1 on 2019-06-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0011_auto_20190626_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
