# Generated by Django 2.1.1 on 2019-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0017_auto_20190626_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='media'),
        ),
    ]
