# Generated by Django 2.1.1 on 2019-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0019_auto_20190626_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.FileField(upload_to='media/source')),
                ('course_id', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('uper_id', models.CharField(max_length=20)),
                ('download_count', models.IntegerField()),
            ],
        ),
    ]
