# Generated by Django 2.1.1 on 2019-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0020_mysource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysource',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
