# Generated by Django 2.1.1 on 2019-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0022_auto_20190626_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysource',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
