# Generated by Django 2.1.1 on 2019-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0024_auto_20190627_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysource',
            name='source_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
