# Generated by Django 2.1.1 on 2019-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0026_mysource_uper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsign',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
