# Generated by Django 2.1.1 on 2019-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0027_auto_20190627_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='id',
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
